export enum Message {
  HEARTBEAT_TIMEOUT = "HEARTBEAT_TIMEOUT",
  TERM_CHANGE = "TERM_CHANGE",
  LEADER_CHANGE = "LEADER_CHANGE",
  LEADER = "LEADER",
  CANDIDATE = "CANDIDATE",
  STATE_CHANGE = "STATE_CHANGE",
}
