CREATE TABLE sankar.aegis(
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    name TEXT,
    url TEXT,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
